title: Sameer Shah # your name (or website title) here
subtitle: Data Scientist
logo: 'images/Sameer_Shah_Profile_min.JPG' # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <label style="font-weight: bold; font-size: large;">Data Scientist</label>
  <label style="font-weight: bold; font-size: large;">Sports Enthusiast</label>
theme: jekyll-theme-minimal
